import { NextResponse } from 'next/server';
import { Pool } from 'pg';
import { requireUser } from '../../../../lib/api-auth';
import { AWARD_APPROVERS, PERFORMANCE_MANAGERS } from '../../../../lib/authorization';

export const runtime = 'nodejs';

async function cycleId(pool: Pool, cycle: string) { const [year, month] = cycle.split('-').map(Number); const q=await pool.query(`SELECT id FROM performance_cycles WHERE cycle_year=$1 AND cycle_month=$2 AND type='MONTHLY' LIMIT 1`,[year,month]); return q.rows[0]?.id??null; }

export async function GET(request: Request) {
  try { await requireUser(PERFORMANCE_MANAGERS); } catch(e){ if(e instanceof Error&&e.message==='UNAUTHORIZED')return NextResponse.json({error:'Forbidden'},{status:403}); throw e; }
  const cycle=new URL(request.url).searchParams.get('cycle'); if(!cycle||!/^\d{4}-\d{2}$/.test(cycle))return NextResponse.json({error:'cycle must be YYYY-MM'},{status:422}); const url=process.env.DATABASE_URL?.trim(); if(!url)return NextResponse.json({error:'DATABASE_URL is required'},{status:503}); const pool=new Pool({connectionString:url,max:5});
  try{const id=await cycleId(pool,cycle);if(!id)return NextResponse.json({error:'Monthly cycle not found'},{status:404});const q=await pool.query(`SELECT ps.employee_id,e.employee_id AS employee_code,e.first_name||' '||e.last_name AS employee_name,ps.overall_score,ps.rank,a.id AS award_id,a.approved_at,b.id AS bonus_id,b.status AS bonus_status FROM performance_scores ps JOIN employees e ON e.id=ps.employee_id LEFT JOIN awards a ON a.employee_id=ps.employee_id AND a.cycle_id=ps.cycle_id AND a.award_type='EMPLOYEE_OF_MONTH' LEFT JOIN bonuses b ON b.award_id=a.id WHERE ps.cycle_id=$1 ORDER BY ps.overall_score DESC,e.last_name,e.first_name`,[id]);return NextResponse.json({data:{cycle,candidates:q.rows.map(r=>({...r,score:Number(r.overall_score),isAwarded:Boolean(r.award_id),approved:Boolean(r.approved_at),bonusStatus:r.bonus_status??null}))}})}finally{await pool.end()}
}

export async function POST(request: Request){let user;try{user=await requireUser(PERFORMANCE_MANAGERS)}catch(e){if(e instanceof Error&&e.message==='UNAUTHORIZED')return NextResponse.json({error:'Forbidden'},{status:403});throw e}const body=await request.json().catch(()=>null) as {cycle?:string;employeeId?:string;overrideReason?:string}|null;if(!body?.cycle||!/^\d{4}-\d{2}$/.test(body.cycle)||!body.employeeId)return NextResponse.json({error:'cycle and employeeId are required'},{status:422});const url=process.env.DATABASE_URL?.trim();if(!url)return NextResponse.json({error:'DATABASE_URL is required'},{status:503});const pool=new Pool({connectionString:url,max:5});try{await pool.query('BEGIN');const id=await cycleId(pool,body.cycle);if(!id)throw new Error('Monthly cycle not found');const score=await pool.query(`SELECT employee_id,overall_score FROM performance_scores WHERE cycle_id=$1 AND employee_id=$2`,[id,body.employeeId]);if(!score.rows[0])throw new Error('Employee has no performance score for this cycle');const existing=await pool.query(`SELECT id FROM awards WHERE cycle_id=$1 AND award_type='EMPLOYEE_OF_MONTH' FOR UPDATE`,[id]);if(existing.rows[0])throw new Error('EOM award already exists for this cycle');const a=await pool.query(`INSERT INTO awards(employee_id,cycle_id,award_type,score,recommended_employee_id,override_reason) VALUES($1,$2,'EMPLOYEE_OF_MONTH',$3,$1,$4) RETURNING id,employee_id,cycle_id,score`,[body.employeeId,id,score.rows[0].overall_score,body.overrideReason?.trim()||null]);await pool.query(`INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,new_value,reason) VALUES($1,'EOM_RECOMMENDED','AWARD',$2,$3::jsonb,$4)`,[user.id,a.rows[0].id,JSON.stringify({employeeId:body.employeeId,cycle:body.cycle,score:score.rows[0].overall_score}),body.overrideReason?.trim()||null]);await pool.query('COMMIT');return NextResponse.json({data:a.rows[0]},{status:201})}catch(e){await pool.query('ROLLBACK');return NextResponse.json({error:e instanceof Error?e.message:'Unable to recommend EOM'},{status:422})}finally{await pool.end()}}

export async function PATCH(request: Request){let user;try{user=await requireUser(AWARD_APPROVERS)}catch(e){if(e instanceof Error&&e.message==='UNAUTHORIZED')return NextResponse.json({error:'Forbidden'},{status:403});throw e}const body=await request.json().catch(()=>null) as {awardId?:string;approve?:boolean;reason?:string}|null;if(!body?.awardId||typeof body.approve!=='boolean')return NextResponse.json({error:'awardId and approve are required'},{status:422});const url=process.env.DATABASE_URL?.trim();if(!url)return NextResponse.json({error:'DATABASE_URL is required'},{status:503});const pool=new Pool({connectionString:url,max:5});try{await pool.query('BEGIN');const a=await pool.query(`SELECT id,employee_id,cycle_id,approved_by,approved_at FROM awards WHERE id=$1 FOR UPDATE`,[body.awardId]);if(!a.rows[0])throw new Error('Award not found');const own=await pool.query(`SELECT id FROM employees WHERE user_id=$1 AND status='ACTIVE' LIMIT 1`,[user.id]);if(body.approve&&own.rows[0]&&String(a.rows[0].employee_id)===String(own.rows[0].id))throw new Error('Self-approval is not allowed');if(a.rows[0].approved_at&&body.approve)throw new Error('Award is already approved');const updated=await pool.query(`UPDATE awards SET approved_by=$2,approved_at=CASE WHEN $3 THEN now() ELSE NULL END,override_reason=COALESCE($4,override_reason) WHERE id=$1 RETURNING id,employee_id,cycle_id,approved_by,approved_at,override_reason`,[body.awardId,user.id,body.approve,body.reason?.trim()||null]);await pool.query(`INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,previous_value,new_value,reason) VALUES($1,$2,'AWARD',$3,$4::jsonb,$5::jsonb,$6)`,[user.id,body.approve?'EOM_APPROVED':'EOM_REJECTED',body.awardId,JSON.stringify({approved_at:a.rows[0].approved_at}),JSON.stringify({approved_at:updated.rows[0].approved_at}),body.reason?.trim()||null]);await pool.query('COMMIT');return NextResponse.json({data:updated.rows[0]})}catch(e){await pool.query('ROLLBACK');return NextResponse.json({error:e instanceof Error?e.message:'Unable to update award'},{status:422})}finally{await pool.end()}}
